---

- hosts:         'deckdb'
  become:        true
  become_method: sudo
  gather_facts:  true
  vars:
    node_version: "14"
  pre_tasks:
    - debug:
        msg:
          - 'inventory_hostname.................: {{ inventory_hostname }}'
          - 'ansible_architecture...............: {{ ansible_architecture }}'
          - 'ansible_distribution...............: {{ ansible_distribution }}'
          - 'ansible_distribution_file_parsed...: {{ ansible_distribution_file_parsed }}'
          - 'ansible_distribution_file_path.....: {{ ansible_distribution_file_path }}'
          - 'ansible_distribution_file_variety..: {{ ansible_distribution_file_variety }}'
          - 'ansible_distribution_major_version.: {{ ansible_distribution_major_version }}'
          - 'ansible_distribution_release.......: {{ ansible_distribution_release }}'
          - 'ansible_distribution_version.......: {{ ansible_distribution_version }}'

  roles:
   - users
   - sudoers
   - ssh
   - chrony
   - common-tools
   - security
   - postfixrelay
   - nodejs


