---

##
## NodeJS
##
## https://github.com/nodesource/distributions#debinstall
##
## curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
## apt-get install -y nodejs
##

- name: NodeJS Apt Key
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present


- name: NodeJS Apt Repo
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version | default('14', true) }}.x {{ ansible_distribution_release }} main"
    state: present
    filename: nodejs


- name: 'apt install nodejs yarn'
  apt:
    name:
      - nodejs
    update_cache: yes
    state: latest


- name: Install yarn
  npm:
    name: yarn
    global: yes









